### ISSUE TITLE
{'error': 'Warning: SessionHandler::read(): Failed to write session lock: A TIMEOUT OCCURRED'}

### ISSUE THREAD

**Issue by sensei73** [jugla/keyatome#13]
A lot of errors today! 
```
Cette erreur provient d'une intégration personnalisée

Logger: custom_components.keyatome.sensor
Source: custom_components/keyatome/sensor.py:452 
Integration: KeyAtome Linky (documentation, issues) 
First occurred: 03:16:00 (141 occurrences) 
Last logged: 17:35:53

day : Missing total value in values: {'error': 'Warning: SessionHandler::read(): Unable to clear session lock record'}
day : Missing total value in values: {'error': 'Warning: SessionHandler::read(): Failed to write session lock: A TIMEOUT OCCURRED'}
day : Missing total value in values: None
month : Missing total value in values: None
week : Missing total value in values: None

```

**Comment by jugla** [comment]
Hello,
I've seen too !
The server seems to be KO . On the smartphone application, it can't display the current consumption.

**Comment by jugla** [comment]
I will see, if I can implement something to slow down request rate on such case !

**Comment by jugla** [comment]
Hello,
I'm implementing somthing that prevents to request live consumption if too many error.
I will see if something harder shall be done next time server errors will occur

**Comment by jugla** [comment]
Implementation done with V5.3.0

**Comment by jugla** [comment]
As non regression tests, no error since 2 days.
I close.
We will see if an error from server occurs
