### ISSUE TITLE
No login available for atome server

### ISSUE THREAD

**Issue by kefrens** [jugla/keyatome#14]
Hi,

I am not able to use the compoment anymore. Everything is unavailable and I get the following error on the log: 2022-05-31 20:48:24 ERROR (MainThread) [custom_components.keyatome.sensor] No login available for atome server

I haven't touched the sensor.yaml where I still have the following:
# Atome LINKY
  - platform: keyatome
    username: myemail
    password: mypassword

Any clues?

**Comment by sicknesz** [comment]
Same here : 
in the log i have 
```
('Login error: Please check your username/password: %s ', '{"error":"Login failed"}')
```
I can tell the API reply with a 401 but why i don't know.

**Comment by jugla** [comment]
I confirm since 19:07 today (31/5/2022) ...
![image](https://user-images.githubusercontent.com/59493499/171290522-a1be06bf-f417-45e5-88ee-1dfc38e500c9.png)

**Comment by jugla** [comment]
It's on server side .... Same issue on Total Energy Android Application (Conso Live).

**Comment by kefrens** [comment]
Thanks.
Quick question, how do you see this? Is there an endpoint to test / URL?
Seems for me the iOS app is working

**Comment by jugla** [comment]
Hello 
,
at 20:35, it works again !

**Comment by jugla** [comment]
> Thanks. Quick question, how do you see this? Is there an endpoint to test / URL? Seems for me the iOS app is working

On android, the total energies app can show you the *conso live*. This one didn't work yesterday.

I reproduce the protocol step by step to see the *401 error*

**Comment by kefrens** [comment]
Ok, its working again (since this morning) and indeed I have been able to reproduce as well using postman with https://esoftlink.esoftthings.com/api/user/login.json

**Comment by jugla** [comment]
Thanks for your feed back !
