### ISSUE TITLE
Issue on keyatome start (issue raise in #17) 

### ISSUE THREAD

**Issue by jugla** [jugla/keyatome#19]
cf. #17, [jedifr](https://github.com/jedifr) reports that after APIv2 update.
Something wrong on keyatome restart : 
- no more sensors

**Comment by jedifr** [comment]
Bonjour,

J'ai trouvé le problème : c'était moi...
J'avais oublié de remettre l'intégration.
Merci pour votre aide.

_English translation:_
_Good Morning_

_I've found the issue: it was me..._
_I 've forgot to put back the integration._
_Thanks for your help._

**Comment by jugla** [comment]
Great.
I close the issue
