### ISSUE TITLE
Previous Value not updated

### ISSUE THREAD

**Issue by jugla** [jugla/keyatome#2]
**Describe the bug**
At midnight, the daily previous value is not updated

**To Reproduce**
1. Wait midnight

**Expected behavior**
Perform the update

**Additional context**
In source code `sensor.py`, it seems that the current value can be set to None : so if it occurs at midnight, None is recorded

**Comment by Vestarija** [comment]
Hi @jugla ,

the issue is back for me, either the refresh stop after 2 hours. You confirm?

**Comment by jugla** [comment]
Hello
This issue is for the new functionnality to record the previous state.

Normally the issue of 2 hours is solved.
Please can you open an issue if confirm . Thus we  can share the logs !

**Comment by jugla** [comment]
Have you installed a temporary patch ? It has been removed if you have installed the latest HA version. If it is the case you have to replace it.

If you install keyatome, don't forget to declare integration in configuration.yaml or via UI.

Thanks in advance for your feedback

**Comment by Vestarija** [comment]
Hey @jugla ,

thanks for you reply. So, I don't understand but after the last update (version core-2021.12.7) this evening the issue disappeared!


All is okay now, I put in my config folder your last release 3.0.0.


Thank you for your job! 🚀🚀🚀

**Comment by jugla** [comment]
close with 3.1.0

**Comment by jugla** [comment]
Thank you very much @Vestarija for your feed back
