### ISSUE TITLE
Atome Daily count error

### ISSUE THREAD

**Issue by LudoARN** [jugla/keyatome#20]
Hello,

I don't know if APIv2 is the problem. But we have a difference between the energy dashboard and the sensor value :

23,46 kWh (wrong) vs 12,528 kWh
![image](https://user-images.githubusercontent.com/81586322/192051473-ee5319bd-19be-4683-84c8-f4dd2ff448b4.png)

![image](https://user-images.githubusercontent.com/81586322/192051400-4f0a0eae-da50-4a86-8bd9-9c84622e5c73.png)

In the log :
------------------------------------------------------------------------------------------------------------------------------------
Logger: custom_components.keyatome.sensor
Source: custom_components/keyatome/sensor.py:536
Integration: KeyAtome Linky (documentation, issues)
First occurred: 20:31:23 (39 occurrences)
Last logged: 21:28:06

Live Data : Missing last value in values: None
Live Data : Missing last value in values: {'error': 'An exception occurred in driver: SQLSTATE[08006] [7] timeout expired'}
Live Data : Missing last value in values: {'error': 'Warning: SessionHandler::read(): Failed to write session lock: A TIMEOUT OCCURRED'}
Live Data : Missing last value in values: {'error': 'Warning: SessionHandler::read(): Unable to clear session lock record'}

------------------------------------------------------------------------------------------------------------------------------------

Cette erreur provient d'une intégration personnalisée

Logger: custom_components.keyatome.sensor
Source: custom_components/keyatome/sensor.py:852
Integration: KeyAtome Linky (documentation, issues)
First occurred: 22 septembre 2022 à 14:45:14 (101 occurrences)
Last logged: 21:44:10

Period are strictly increasing except reset to zero

Do you have a solution ?
Thanks for your job 👍

**Comment by jugla** [comment]
Hello,
The energy dashboard works by computing each delta of "daily sensor".
If the data is increasing, the dash board and daily are ok. Otherwise, you get steps and it's wrong.
That's why , I set an error in such case (i.e decreasing) and remove the wrong data.

In the logs, near the messages `Period are strictly increasing except reset to zero`, you have former and new value.
Please can you send me, to get a clue?

**Comment by jugla** [comment]
By the way, is there a "chance" that you have "rebooted" HA during the interval (in the gap/drop).
I guess there is something wrong (I correct it for next version)

**Comment by LudoARN** [comment]
Hello,

i'm sorry but i don't find the new value near "Period are strictly increasing except reset to zero" (maybe because i'm not a HA power user). I can't help you.

And it's not a reboot too. It works fine this day ... strange

**Comment by jugla** [comment]
Hello @LudoARN ,
Please can you test 7.3.0 .
I have change the way to detect change of day and so the increasing/decreasing detection

**Comment by jugla** [comment]
Hello @LudoARN ,
The release 7.4.0 will make data sever more robust (week and month sensors, will be improved).
Thanks in advance for your feed back on 7.3.0 .
7.4.0 is under test.

**Comment by beromont** [comment]
Hi @jugla,
i don't know if that help you but I also have often "HandleNonIncreasingValueError" on 7.3.0 :

![image](https://user-images.githubusercontent.com/4980078/192308597-a3b17fe4-3d56-4229-bbd2-462d9c7009e5.png)

But there is no former or new value in the logs :

![image](https://user-images.githubusercontent.com/4980078/192308343-ef126f36-dc46-4a8e-90a3-b97ae8c9f627.png)

I'll wait for 7.4.0 :)

**Comment by jugla** [comment]
Hello,
Thanks for your feed back.
Today we get a lot of error on server side ...
In 7.4.0, the integration is less vebose on non increasing value and force the things. As a result, week, month value are more available.
I fully take into account that server messages can have other value than the one expected (i.e. no consumption).

**Comment by jugla** [comment]
7.4.0 is avaible, wait for couple of hours to get it from server.

**Comment by beromont** [comment]
It works perfectly with 7.4. Thank you jugla :)

**Comment by LudoARN** [comment]
same conclusion for me, very good job.
Thanks.
