### ISSUE TITLE
ToManyServerError & no data

### ISSUE THREAD

**Issue by joebarteam11** [jugla/keyatome#21]
Hi there,

Impossible to pull any data :(

Got the "ToManyServerError" log message 
![image](https://user-images.githubusercontent.com/85874120/200193717-69f4a95e-5bfc-4730-8d9f-7b922a349885.png)

Running HA 2022.11.1
Supervisor 2022.10.2

Am I the only one having this issue ?

**Comment by jugla** [comment]
Hello,
I got some error around 21:15, and it's fine now.
![image](https://user-images.githubusercontent.com/59493499/200198071-566f2af0-565f-41b5-9061-966edc8c94c3.png)

**Comment by jugla** [comment]
Any news ?
Is it like #22

**Comment by joebarteam11** [comment]
> Hello,
> I got some error around 21:15, and it's fine now.
> ![image](https://user-images.githubusercontent.com/59493499/200198071-566f2af0-565f-41b5-9061-966edc8c94c3.png)

I'll try this evening & I'll let you know

**Comment by joebarteam11** [comment]
Still the same problem, do I need to add a sensor in my configuration.yaml as mentioned [here](https://www.home-assistant.io/integrations/atome/) or is it deprecated ?
HA runs on a VM, can this introduce communication problems?

Here is a screenshot of the Atome Device
![Image 08-11-2022 à 23 03](https://user-images.githubusercontent.com/85874120/200685605-831516ef-72aa-48a6-84e2-ac9ecdb4007b.jpg)

Thanks for help !

**Comment by jugla** [comment]
Hello,
Please , have you tried to restart HA ?
NB : `configuration.yaml` is deprecated. Use UI . It's just kept to be backward compatible.
I think it is stuck on login (the server was down, and no retry implemented)

**Comment by jugla** [comment]
Except if something wrong in routing message within VM, normally no issue due to VM.

**Comment by joebarteam11** [comment]
Yes I tried several times to restart, reinstall, etc...
It's strange, I get a successful login message and I get my contract number (hidden in red on my previous screenshot) but I can't get any data.

I don't know if this is "normal" but my key disconnects quite often, the led goes from flashing green to white to red, sometimes it reconnects and sometimes it doesn't and I have to do it manually via the app.

I guess it's not a wifi problem since my router is right under the Linky, about 15cm...

**Comment by joebarteam11** [comment]
* Quite often means up to twice a day

**Comment by joebarteam11** [comment]
Here is a part of the logs :
```
2022-11-11 11:39:47.770 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration keyatome which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-11-11 11:40:07.231 ERROR (MainThread) [custom_components.keyatome.sensor] No login available for atome server
2022-11-11 11:48:35.358 WARNING (SyncWorker_1) [custom_components.keyatome.sensor] Live Data : Missing last value in values: {'isConnected': False, 'time': '2022-11-11T11:48:35+01:00', 'timeLimitBeforePowerFailure': -1}
2022-11-11 11:48:36.514 ERROR (SyncWorker_1) [custom_components.keyatome.sensor] Live Data : Missing last value in values: {'isConnected': False, 'time': '2022-11-11T11:48:36+01:00', 'timeLimitBeforePowerFailure': -1}
```

**Comment by jugla** [comment]
Hello,
In the log, you have `No login available for atome server`. It means that the server is not reachable or you have no credential.
That explains why you have no nothing.
Normally, Andriod/Apple Apps shall be consistant (except if there is a cach algorithm)

I don't know what is your network configuration. At a time, I fall on this "issue", that seems to be yours.
I have a freebox with the "freebox repeteur" : the "freebox repeteur" is at less that 2 meters from linky atome key.
At linky configuration (physical atome key), the wifi was catched on "freebox repeteur" (the atome key led was green).
From time to time, the atome key goes red --> it falls on freebox server wifi (that was less strength but enough strength to be catched) : I was stuck.
I have build another wifi network to force linky atome key to catch the new one.
If you have a freebox, or another wifi network, you can check where the linky atome key is connected.

If you can assess that if the linky atome key goes green led , and then if you restart HA keyatome, then everything goes ok, I will give a look on a evolution.

By the way, if the issue is on physical key atome, have you reset the configuration and re-install it ?

**Comment by LHOriginal76** [comment]
I had exactly the same problem suddenly I uninstalled the integration and now impossible to reconnect. I got an "Unknown error occurred" error message. Small passage from my error log:   
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/fake_useragent/utils.py", line 139, in load
    browsers_dict[browser_name] = get_browser_user_agents(
  File "/usr/local/lib/python3.10/site-packages/fake_useragent/utils.py", line 123, in get_browser_user_agents
    raise FakeUserAgentError(
fake_useragent.errors.FakeUserAgentError: No browser user-agent strings found for browser: chrome

**Comment by joebarteam11** [comment]
> I don't know what is your network configuration. At a time, I fall on this "issue", that seems to be yours. 

I finally found the reason for the daily disconnection: a wifi power saving setting on my router was causing the connection problem. 
After that, I went into the app to check if I could access my data, and I could after giving my credentials to the esoftthings login page that appears in the app. (so that means my credentials exist)

I then restarted the KeyAtome integration, but still the same message: `ToManyServerError`.
But I noticed something in the HA logs: The `Atome_Login_Stat` is not my current client number, but my previous one (I moved recently BUT I didn't have the atomic key in my old home). I don't know why since I ordered the key when I arrived in my current home with my new customer number...

**Comment by LudoARN** [comment]
Hello,

Forget the VM or wifi, the problem comes from a new captcha in Total Energy  (a new API version ?) :

![image](https://user-images.githubusercontent.com/81586322/201541301-b9c63351-e687-44bf-98a8-78dfa0cc8861.png)

**Comment by jugla** [comment]
Hello @joebarteam11 ,
>I then restarted the KeyAtome integration, but still the same message: ToManyServerError.
But I noticed something in the HA logs: The Atome_Login_Stat is not my current client number, but my previous one (I moved recently BUT I didn't have the atomic key in my old home). I don't know why since I ordered the key when I arrived in my current home with my new customer number...

If you have kept your user ID, maybe you can look if you have several linky attached. (In login stat, attribute `list_user_reference`
)
![image](https://user-images.githubusercontent.com/59493499/201545793-77eaafb2-5385-413e-bd7b-883a3ab8e388.png)


If it is the case, at configuration, choose the linky number (i.e. your new house !)

Hope it will work !

**Comment by jugla** [comment]
Hello @LudoARN ,
I got also an issue, il will see your suggestion API vX ...

**Comment by jugla** [comment]
Ok I see what stuck the integration.
If for any reason , the first login is denied then the integration stops asking.
I will add something.
As a workaround, manually restart HA.

If login failed, in the logs you have : 
`2022-11-10 16:58:04.926 ERROR (MainThread) [custom_components.keyatome.sensor] No login available for atome server`

If login granted, if debug level activated in configuration.yaml, in the logs you have : 
`2022-11-13 22:34:09.633 DEBUG (MainThread) [custom_components.keyatome.sensor] login user reference is XXXXXXXXX`
`2022-11-13 22:34:09.634 DEBUG (SyncWorker_2) [custom_components.keyatome.sensor] Login Stat Data : Perform login`

**Comment by LudoARN** [comment]
Hello Jugla,

It works for 1 hour after a second restart i don't know why.

2022-11-14 21:12:16.723 DEBUG (MainThread) [custom_components.keyatome.sensor] login user reference is XXXX
2022-11-14 21:12:16.725 DEBUG (SyncWorker_7) [custom_components.keyatome.sensor] Login Stat Data : Perform login
2022-11-14 21:12:30.347 DEBUG (SyncWorker_7) [custom_components.keyatome.sensor] Updating Atome Login data. ID: XXXXX, REF: 110624191
2022-11-14 21:12:30.350 DEBUG (MainThread) [custom_components.keyatome.sensor] Finished fetching keyatome data in 8.626 seconds (success: True)
2022-11-14 21:12:30.351 DEBUG (SyncWorker_5) [custom_components.keyatome.sensor] Live Data : Update Usage
2022-11-14 21:12:30.567 DEBUG (SyncWorker_5) [custom_components.keyatome.sensor] Updating Atome live data. Got: 960.000000, isConnected: True, subscribed: 6000
2022-11-14 21:12:30.570 DEBUG (MainThread) [custom_components.keyatome.sensor] Finished fetching keyatome data in 0.219 seconds (success: True)
......

**Comment by jugla** [comment]
Thanks @LudoARN for your feed back.

[Edited] Finally, the login has to be performed to retrieve user_ref. After it will be a mess. I prefer to let integration failed after 1rst start if login wrong.

**Comment by joebarteam11** [comment]
Hi there !

It’s finally working !

I removed & re installed the integration, but specified « 2 » in the third field instead of « 1 » as I did so far.
And I could finally see data rising.

![462AEBD7-7D48-454C-8DE8-0FF51852C05C](https://user-images.githubusercontent.com/85874120/201768711-b9e0df5e-417a-457d-b824-fe24ef07b064.jpeg)
 
Many thanks for help 😉

**Comment by jugla** [comment]
Great !

**Comment by jugla** [comment]
@LudoARN , I will add a feature to restart on last login info if they are unavailable !
So that keyatome integration won't be stuck on 1rst step if sever issue --> we will get a periodic request :-)
