### ISSUE TITLE
KeyAtome Config Flow : No login available for atome server

### ISSUE THREAD

**Issue by birse29** [jugla/keyatome#22]
Hello,

I am using latest version of HA & keyatome. Everything was fine until yesterday, no data received anymore.
I tried to remove the integration and reconfigure it but still the same error message

2022-11-07 21:37:19.985 ERROR (MainThread) [custom_components.keyatome.config_flow] KeyAtome Config Flow : No login available for atome server

I have checked my creds, it works on both iPhone app and computer web browser.

Do you have any idea ?

**Comment by jugla** [comment]
I think TotalEnergies performs some evolution on server side.
I have also error this evening ....
![image](https://user-images.githubusercontent.com/59493499/200422491-5f6fb3d0-4949-4888-a3b0-baccdbcd5f24.png)

**Comment by jugla** [comment]
Total Energies Android apps is not responding (conso live)

**Comment by birse29** [comment]
I confirm it was on their side, this morning it works well again.

**Comment by jugla** [comment]
Thanks for your quick feed back !
