### ISSUE TITLE
Using both phone app & HA's keyatome ?

### ISSUE THREAD

**Issue by dpatou** [jugla/keyatome#23]
Hello there,

First and foremost, thanks for making this integration working (again), it's cool work.

I'm not sure how this should be filed but I've been having issues : When I use this integration, I can't use the phone app, the data in is empty.

After some testing it seems to be that credentials generated at login on phone are made invalid as soon as HA queries the API. Logging out on app, then logging back in restores the app power update, which then gets disabled again at next live update in HA (every 30s).

Since we're using the app to monitor costs (can't yet get the wife to go full HA), it prevents me from using this integration.

Is there a way around this ?
I tried editing const.py to make polls of live power  more spaced but it just makes the issue happen less often.

Cheers if anyone can shed any light on this.

**Comment by jugla** [comment]
Thanks for your feed back :-)

Strange, I have not this behaiour on my side .... 
I set "remenber me" option on Phone App . Is it enough ?
NB : My Phone App is on Android.

Tell me

**Comment by jugla** [comment]
Hello  @dpatou ,
Please can you try with the latest version v7.4.1 ?

**Comment by dpatou** [comment]
Hey @jugla
I updated to v7.4.1, and checked on my app (i'm on android too, using the app called "atome"), I have no "remember me" option to tick.

When I open my app I get the live power (and other data), as soon as the HA update "ticks" my phone app stops showing data (unavailable - indisponible in app).

If I logout in the phone app, then log back in I get the first update up until first HA update "tick".

**Comment by jugla** [comment]
Hello,
"atome" application is legacy.
You have to move to "TotalEnergies Electricté&Gaz".

You will have new graphs :  
- conso temps reel : Live / Heure / Jour
- suivi conso : heure / jour / mois / année / Mes Objectifs

Tell me !

**Comment by dpatou** [comment]
Oh wow I feel stupid. Thanks for pointing out and helping, it works great
