### ISSUE TITLE
fake_useragent.errors.FakeUserAgentError: No browser user-agent strings found for browser: chrome

### ISSUE THREAD

**Issue by roman-beylin** [jugla/keyatome#24]
Hello, 

Thanks a lot for integration. 

After last reboot (in my case was update to 2022.12.1) an error appear in keyatome.
I thought last update break something but i rollback to previous version and have same error.

Looks related to external, but not sure for a fix.

Logger: homeassistant.components.sensor
Source: custom_components/keyatome/sensor.py:191
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 10:48:23 (1 occurrences)
Last logged: 10:48:23

Error while setting up keyatome platform for sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/fake_useragent/utils.py", line 139, in load
    browsers_dict[browser_name] = get_browser_user_agents(
  File "/usr/local/lib/python3.10/site-packages/fake_useragent/utils.py", line 123, in get_browser_user_agents
    raise FakeUserAgentError(
fake_useragent.errors.FakeUserAgentError: No browser user-agent strings found for browser: chrome

It looks related to unavailbity of https://useragentstring.com/pages/chrome/ and fallback 
https://useragent.melroy.org/cache.json

Do you have any idea how to fix this?

Thanks a lot for your help.

**Comment by BenoitAnastay** [comment]
The fix might be easy, we can use another agent as argument, I'm not on my computer but I have the same issue.

I'll check this later if not resolved by someone else.

**Comment by jugla** [comment]
Hello,
@BenoitAnastay @roman-beylin 
I will do a first patch , I've not seen that user-agent package is quite old in the release ...

**Comment by tcavin** [comment]
Hi @jugla 
First of all, many thx for this integration !
Same problem here related by @roman-beylin 
Thx for your coming help

**Comment by jugla** [comment]
Keyatome v7.4.1 is pusblished : tell me if it improves the things

**Comment by BenoitAnastay** [comment]
Seems fixed

**Comment by tcavin** [comment]
You rock ! Solved on my side too. Thx @jugla !

**Comment by jugla** [comment]
Thanks !
