### ISSUE TITLE
Disconnect sometimes

### ISSUE THREAD

**Issue by JeedHome44** [jugla/keyatome#27]
Hello,

Your integration work but disconnect sometimes like atome.

Can we do reload if 30 minutes without change ?

If yes, how please ?

**Comment by jugla** [comment]
If it seems to be stuck, you can make an HA automatisation and force a reload with `Home Assistant Core Integration: reload_all` (service section)

Internally, keyatome performs retry (i.e. log on server) once if a command does not respond .
Automatically reconnect every 1h30.

Can you show me the "Diagnostic" sensor curve ?

Thanks in advance

**Comment by jugla** [comment]
Any news ?

**Comment by JeedHome44** [comment]
Hello,
I'm waiting for it to start again to tell you the problem.
it is not possible that it is displayed as an integration with the "Reload" button?
Thank you

**Comment by JeedHome44** [comment]
Voici le problème qui recommence:
https://i.postimg.cc/qh95VsYn/Capture.png

**Comment by jugla** [comment]
Est-ce que vous pouvez récupérer qqch dans les traces ?
Qu'est-ce qu'indique le senseur Atome_Diagnostic ?

**Comment by JeedHome44** [comment]
Can I do debug info ?

**Comment by jugla** [comment]
yes

**Comment by jugla** [comment]
Please can you look in diagnostic, if there is something on server side ?

**Comment by JeedHome44** [comment]
How do I download the diagnostic?  I don't see KeyAtome as an integration

**Comment by JeedHome44** [comment]
i can't find KeyAtome in Integration page. So i can't find config_entry to do reload like that:
http://localhost:8123/api/config/config_entries/entry/XXXXXXXXX/reload
Can you update it to see it in integration page ?

**Comment by jugla** [comment]
Hello
Please how have you configured keyatome : 
- via config flow
- or via configuration.yaml?
Just to be sure: you have configured keyatome and not atome (default ha integration).
If you have configured via configured flow, you shall see in integration page .
Thanks in advance.

**Comment by JeedHome44** [comment]
Thank you !
I have configured with yaml. i just do with config flow !
i can do now reload integration !

**Comment by jugla** [comment]
great I will close the issue. If ok with you
