### ISSUE TITLE
Atome Live Power no more updated

### ISSUE THREAD

**Issue by chmtc94** [jugla/keyatome#29]
**Describe the bug**

Atome Live Power no more updated (freezed) since 26/08/2023 20:23 when Atome_daily still always right updated, and led on Linky's key always flashing green, and live power always right live updated on Consolive TotalEnergie smartphone app

**To Reproduce**
Just see updates and history

**Expected behavior**

**Screenshots**
https://e.pcloud.link/publink/show?code=XZOMD2Z7ICkRv0q6jB8tTlqI26q2XE8QPpy

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
HA OS 10.5
HA CORE 2023.8.4 (26/08/2023 07H30)

**Comment by chmtc94** [comment]
Curiously, restarting HA seems to have solved the problem 🤔🤔
I propose to close the issue ...

**Comment by jugla** [comment]
Hello,
If by the way, you have the previous logs ?
When you have reboot, you have forced : 
- reinit HA-AtomeServer link
- reinit HA process
- reinit KeyAtome process.
Thanks in advance

**Comment by chmtc94** [comment]
Hi @jugla
Following the HA log files home-assistant.log and home-assistant.log.1 filtered with "atome" in the line of the home-assistant log files.
For your information, such errors were regularly present since the installation of the integration many months ago, but it was the first time I have the permanent error described when the Linky key is blinking green...
I also have sometime problems with the Linky key itself that TotalEnergies has not yet resolved. The key sometime disconnect from server and enter in a loop to try to reconnect itself. The duration of the loop may vary from hours to days.... Hopefully I found that when I disconnect physically the key and reconnect it, it succeed reconnecting to the server in a maximum of 5 minutes without entering the infernal loop... The loop consist in connecting the Linky key to the WIFI network, wich I saw succeed immediately (and with a very good flow connection status), and 10 sec later disconnecting the key following a probable connection error to the TotalEnergies servers, and then, 1mn30 later, connecting again successfully to the WIFI network, etc...  
I was living with that until now, but I was seriously considering changing the TotalEnergies Linky key by a Lixee Key... Do you have any experience of that ?
In all case, thank you for your job with the keyatome integration.
I would have been interested in knowing all fields accessible (via a template entity for example, as for the prices) and especially the respective energies (and costs) in high cost hours and low cost hours. Could you please tell me what is possible ? Thanks in advance.
[atome-linky.log](https://github.com/jugla/keyatome/files/12522398/atome-linky.log)
[atome-linky.log.1.log](https://github.com/jugla/keyatome/files/12522399/atome-linky.log.1.log)

**Comment by chmtc94** [comment]
PS : Maybe would you be also interested by the attached Linky-Diagnostic entity history during the period
(NB : Blue in the diagrams are for HandleNonIncreasingValueError periods)

Best regards

[Linky-Diagnostic.pdf](https://github.com/jugla/keyatome/files/12522835/Linky-Diagnostic.pdf)

**Comment by jugla** [comment]
Thanks for your feed back.
Sorry or the delay.
I've experienced, some issue on Wifi with the freebox because "behind a 'big' wall".
What I've done is to add a wifi repeater close "linky".

**Comment by jugla** [comment]
I close the issue. Fell free to open a new one, if it occurs again
