### ISSUE TITLE
Check of the credentials

### ISSUE THREAD

**Issue by philochardbleu** [jugla/keyatome#3]
It seems that whatever are the credentials (ident and password) on the UI, all are accepted, and change is only possible trough delete and  new integration. Regards.

**Comment by jugla** [comment]
Hello
I have implemented the password checks after the creation of the integration : currently there is no checks at UI level.
To change the password, as you said, you have to delete the integration.

I will see how to handle your request (wait a little as it does not prevent from using the integration)

**Comment by jugla** [comment]
Hello
I've implemented the credentials checking in UI in V3.5.0

**Comment by philochardbleu** [comment]
Nice enhancement ! Thank you !

Le 08/01/2022 à 23:13, jugla a écrit :

**Comment by jugla** [comment]
Thanks :-)
