### ISSUE TITLE
more connection with KeyAtome integration

### ISSUE THREAD

**Issue by Dgigie** [jugla/keyatome#30]
hello since today the integration no longer works apparently no more access to the server
I tested with the total energy application and everything works correctly

"Atome_Diagnostic changé en TooManyServerError"

![KeyAtome](https://github.com/jugla/keyatome/assets/128133018/5d68a594-bdd3-44f0-b71c-b850d905563b)
.'

Home Assistant 2023.9.3
Supervisor 2023.09.2
Operating System 10.5
Interface utilisateur : 20230911.0 - latest

in any case thank you again for this superb integration

**Comment by Dgigie** [comment]
apparently there must have been a problem during the day because everything is back to normal, thanks anyway

**Comment by wodoz** [comment]
Hi, new install and same issue : 
![image](https://github.com/jugla/keyatome/assets/6433494/05414357-20c1-4e55-ad47-b27b798ea829)

i'm sure about my credential,

**Comment by sabouarthur** [comment]
Hi all,

I m facing same issue with this integraion. and cannot figure out that s goning on.
randomly I have the error message saying TOO many ERROR .... like describe in this topic. If I unstall and install it again it comes back for a few time and than the integration is not working anymore.

Am I alone ??

**Comment by SergeyAnokhin** [comment]
Resolved by remove/add integration. 

It may be happened after adding second linky to my electricity provider.

![image](https://github.com/jugla/keyatome/assets/31309051/f5ef71ab-40f3-495d-beed-e50844edb063)

**Comment by sabouarthur** [comment]
If you have two or more houses and only one atome device you should select 1 st or 2nd atome key

**Comment by ekain-fr** [comment]
Hello,

I'm also facing the "TooManyServerError" issue.
I removed the integration, restarted HA, added the integration, restarted HA again... Same issue.
![CleanShot 2024-02-24 at 12 00 51@2x](https://github.com/jugla/keyatome/assets/95979087/38652779-604c-4f23-91d3-598051a3a9f2)

Based on the message it seems that the integration should try to limit the rate of API calls to avoid being throttled.

**Comment by ekain-fr** [comment]
Hello again,

My bad: I resolved the issue by:
- Opening Settings > Integrations > Key Atome.
- Removing the existing integration entry.
- Adding again an integration entry, configured with same username / password, **BUT WITH atome key number 2** instead of the default 1. (as suggested [here](https://github.com/jugla/keyatome/issues/30#issuecomment-1939369838))

After this change I'm no longer getting the TooManyServerError message and all sensors populate with expected values (previously the sensors would all report _"unknown state"_).

Hoping this message could help anyone facing similar issue.

Cheers!

**Comment by jugla** [comment]
Thanks for the support

**Comment by sabouarthur** [comment]
Thanks , just would like to add a ticks :

If for any reason you select, in your mobile apps TOTAL Account, another contract you should  reactivate your integration in HA

best regards

**Comment by jugla** [comment]
Add server section in general description https://github.com/jugla/keyatome
