### ISSUE TITLE
Installation by HACS doesn't work

### ISSUE THREAD

**Issue by minscof** [jugla/keyatome#31]
**Describe the bug**
I try to install this integration in HACS by the UI

**To Reproduce**
The doc says : Press add icon and search for keyatome

but the search returns nothing with this keyword : keyatome

**Expected behavior**
Installation works by UI.

**Desktop (please complete the following information):**
 - OS: Raspberry OS
 - Docker installation of HA
 - Version HA : Home Assistant 2023.10.5

**Comment by jugla** [comment]
Sorry for the delay.
Have you found the issue ?
First step : install HACS (perhaps, you have already done)
Second step : then install keyatome via HA "install new integration"

**Comment by minscof** [comment]
Thank you for your help.
It works now.
