### ISSUE TITLE
POWER_WATT will be deprecated in HA Core 2025.1.

### ISSUE THREAD

**Issue by aubierr** [jugla/keyatome#33]
Good morning,

I am pointing out this which is showing up as a warning in the logs.
Is it possible to update?

POWER_WATT was used from keyatome, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead

Thank you

**Comment by jugla** [comment]
Thanks for your feedback, I will remove deprecated

**Comment by jugla** [comment]
Thanks for your modification !

**Comment by jugla** [comment]
Sorry for the delay , I publish your modification
