### ISSUE TITLE
Unable to prepare setup for platform keyatome.sensor

### ISSUE THREAD

**Issue by forzewin** [jugla/keyatome#5]
Intregration is not working

**To Reproduce**
Reboot after installing keyatome integration using HACS

Logs 

Logger: homeassistant.setup
Source: setup.py:317
First occurred: 14:27:26 (1 occurrences)
Last logged: 14:27:26

Unable to prepare setup for platform keyatome.sensor: Platform not found (cannot import name 'SensorDeviceClass' from 'homeassistant.components.sensor' (/volume2/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/sensor/__init__.py)).

**Comment by jugla** [comment]
Hello
Thanks for using the components !
Please can you tell me which version of HA you are using ?

**Comment by forzewin** [comment]
Hi Jugla,

I am using Home Assistant 2021.9.7.

It is a Home assistant core version, the latest one available for synology NAS.

**Comment by jugla** [comment]
Ok
As far as I remenber, the SensorDeviceClass is introduced by HA2021.11.x .
I'm using also core version but on raspberry PI.

I don't know if you can force an upgrade ?

**Comment by forzewin** [comment]
Unfortunately i dont think it is possible on Synology system, but i will dig into it.

Thank you for your support. :)

**Comment by jugla** [comment]
Thanks !
I will close the the issue.
Let me know if you succeed in installing the new HA release
