### ISSUE TITLE
Atome sensors have stopped working (several subscriptions)

### ISSUE THREAD

**Issue by tofgun** [jugla/keyatome#8]
**Describe the bug**
Atome sensors have stopped working ...

2022-02-02 22:17:59 WARNING (SyncWorker_4) [custom_components.keyatome.sensor] Live Data : Missing last value in values: {'isConnected': False, 'time': '2022-02-02T22:17:59+01:00', 'timeLimitBeforePowerFailure': -1}
2022-02-02 22:18:00 ERROR (SyncWorker_4) [custom_components.keyatome.sensor] Live Data : Missing last value in values: {'isConnected': False, 'time': '2022-02-02T22:18:00+01:00', 'timeLimitBeforePowerFailure': -1}

**Screenshots**
![image](https://user-images.githubusercontent.com/77484063/152239166-a58af510-65ba-4c15-a3f5-486b7e51a77f.png)

![image](https://user-images.githubusercontent.com/77484063/152240458-a0425b6f-f19c-4607-a961-fe3a53c526b8.png)

![image](https://user-images.githubusercontent.com/77484063/152241917-805073a1-0240-452f-9a2d-39212fce6b1f.png)

**Comment by jugla** [comment]
Hello,
Thanks for your report.

When `{'isConnected': False, 'time': '2022-02-02T22:17:59+01:00'`, it means that the linky is not connected , but TotalEnergy server still answers.
Please can you check on total energy application if everything is going well ?

**Comment by jugla** [comment]
Pease have you several subscriptions within your account ?

**Comment by tofgun** [comment]
Yes, I have 4 subscriptions in my account. Only the first one has a key
atome.

**Comment by tofgun** [comment]
I have checked with the Android Atome app and I would say it does not work
(I saw this after the last keyatome integration release) but I did not care
as I had the data from HA. But now I have nothing from both sides :-( :
In the android atome app,I have the "realtime" data during some seconds and
after it seems to be disconnected. If I switch between the different tabs
of the app, the data are not refreshed and then I finally have the login
form that appears.

**Comment by jugla** [comment]
Hello,
An hint : can you check the light on the atome (linky).
It must green to be connected to the server. (Perhaps you already know)

**Comment by tofgun** [comment]
Hi the LED is green and flashing which means it is correctly functionning

**Comment by jugla** [comment]
I'm puzzled : 
- linky LED is ok
- the android apps is ko
Let's wait a little if on server side, they solve the issue.

**Comment by tofgun** [comment]
I will contact the Total support to ask.

**Comment by tofgun** [comment]
For my knowledge, is the key atome integration using the
https://esoftlink.esoftthings.com/login web service ?

**Comment by tofgun** [comment]
I have discussed with the support. If I understood correctly they want to
progressively remove the atome application and to replace it with the
"conso live" available in the totalenergies android application. Could it
be that they have cut off the service for me ?:

I cant connect anymore to the atome api service
https://esoftlink.esoftthings.com/login and the atome android app is not
working more than 5 seconds.
The conso live of the totalenergies android app is working correctly.

**Comment by jugla** [comment]
Hello,
I've moved towards their new application.
It still work for me.
https://esoftlink.esoftthings.com/login is not intended to be used directly. This link is used by application.

*Just to try can you check if by declare under UI, keyatome for link1 /2 /3 and 4, one gives live consumption.*

Definitively I have to add a sensor showing which subscription it retrieves

**Comment by tofgun** [comment]
some time ago, a successful login was redirecting to some atome pages like :
/graph-query-last-consumption
/profile
/logout
... etc but it does not work anymore

You were right to ask to try as it works now with link number 3 => I have
my atome data integrated into HA.
 I dont know why suddenly during Tuesday night, the atome service suddenly
changed ...

Cheers,
Christophe

**Comment by jugla** [comment]
Thanks for your feedback.
I will see how to implement a sensor to know which subscription it has been taken.
Currently, I put the user ref in attribute of live sensor.

Philippe

**Comment by tofgun** [comment]
It is back :-(

2022-02-04 18:16:02 WARNING (SyncWorker_0)
[custom_components.keyatome.sensor] Live Data : Missing last value in
values: {'isConnected': True, 'time': '2022-02-04T18:16:02+01:00',
'timeLimitBeforePowerFailure': -1}2022-02-04 18:16:03 ERROR
(SyncWorker_0) [custom_components.keyatome.sensor] Live Data : Missing
last value in values: {'isConnected': True, 'time':
'2022-02-04T18:16:03+01:00', 'timeLimitBeforePowerFailure': -1}

**Comment by jugla** [comment]
The atome is connected on server.
But not given data ....

**Comment by jugla** [comment]
Can you wait a little.
If still there, restart HA and tell me if it works

**Comment by tofgun** [comment]
I have the problem with the Android atome app and the conso live app ... it
seems to be a Total service issue.

You dont have the same problem ?

**Comment by jugla** [comment]
No it works fine at home ...

NB: I have lot of pb at a time since atome disconnects from my wifi router. I put a wifi router closer, and now no more issue.

**Comment by jugla** [comment]
@tofgun , please see #9

**Comment by tofgun** [comment]
I phoned again to the Total support as the Live Power was not working. They
told me that they were experiencing a service issue this week, it is not
yet solved and they are working on it.
We have to wait expecting that it will solve the keyAtome as well.

**Comment by jugla** [comment]
Thanks a lot for your feedback

**Comment by jugla** [comment]
it's now ok for me

**Comment by jugla** [comment]
In keyatome V5.0.0 , I have added a "login_stat" sensor . Thus you can check the user_ref to know if you have addressed the right linky.

**Comment by jugla** [comment]
Hello, in keyatome V5.1.0, I have added the list of user reference within the user account.

**Comment by tofgun** [comment]
My data are back since ~14h today. 
Many thanks for the new features, they are very useful.

**Comment by jugla** [comment]
Thanks for your feed back :-)
